FROM node:22-bookworm-slim

ENV NODE_ENV=production

RUN apt-get update \
  && apt-get install -y --no-install-recommends curl zip unzip \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY node_modules ./node_modules
COPY apps/api ./apps/api
COPY packages/shared-contracts ./packages/shared-contracts

WORKDIR /app/apps/api

EXPOSE 3000

CMD ["node", "dist/main.js"]
